# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Victor
brief-intro: You know, I see
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://v-i-c-t-o-r.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  V-I-C-T-O-R
email: victordestiny1990@gmail.com
weibo_username: 
zhihu_username: v-i-c-t-o-r
linkedIn_username: 
dribbble_username:

description_footer: 本站记录我人生之旅的沿途风景！

# comments
# short_name 多说不可用，可以用Valine/gitalk这两款评论插件
# 配置教程https://www.codepeople.cn/2019/01/03/Jkeyll-Valine/
duoshuo_shortname: 
disqus_shortname: 
valine_shortname: 
    enable: true
    appId:  TsxJfHDPmBBYA4TdyzhU2YID-gzGzoHsz
    appKey: 85WLfeJbyV9AqbMt6jKUS6nV
    notify: true # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    avatar: monsterid
    guest_info: nick,mail,link
    placeholder: "孤以为卿必有高论！"

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 2e576caadd4d94da253900dec02b2fbc
google_analytics_id: UA-167353534-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt 这特么是摘要,尴尬，加入到所有文章中即可
excerpt_separator: "<!-- more -->"

# paginate
gems: [jekyll-paginate]
paginate: 6
